/**
 * ERP Knowledge Base & Deterministic Step Engine
 * ================================================
 * Architecture Layer: Business Logic Layer
 *
 * Contains:
 *   1. Verified troubleshooting steps database (NOT generated by LLM)
 *   2. Mock ERP data (invoices, POs, users, etc.)
 *   3. Deterministic step engine for data lookups and resolution
 *   4. Escalation decision logic
 */

// ═══════════════════════════════════════════════════════════════════════════
// Mock ERP Database
// ═══════════════════════════════════════════════════════════════════════════

export const INVOICES = {
  "INV-001": {
    id: "INV-001",
    vendor: "Acme Corp",
    amount: 12500.0,
    currency: "USD",
    status: "Paid",
    due_date: "2026-02-15",
    paid_date: "2026-02-10",
    po_number: "PO-4520",
    department: "Procurement",
  },
  "INV-002": {
    id: "INV-002",
    vendor: "Global Supplies Ltd",
    amount: 8750.5,
    currency: "USD",
    status: "Pending Approval",
    due_date: "2026-03-10",
    paid_date: null,
    po_number: "PO-4535",
    department: "Operations",
  },
  "INV-003": {
    id: "INV-003",
    vendor: "TechParts Inc",
    amount: 3200.0,
    currency: "USD",
    status: "Overdue",
    due_date: "2026-02-20",
    paid_date: null,
    po_number: "PO-4510",
    department: "IT",
  },
  "INV-123": {
    id: "INV-123",
    vendor: "Office Essentials",
    amount: 950.75,
    currency: "USD",
    status: "In Transit",
    due_date: "2026-03-05",
    paid_date: null,
    po_number: "PO-4501",
    department: "Admin",
  },
};

export const PURCHASE_ORDERS = {
  "PO-4501": {
    id: "PO-4501",
    vendor: "Office Essentials",
    status: "Shipped",
    items: ["Printer Cartridges x10", "A4 Paper x50 reams"],
    total: 950.75,
    expected_delivery: "2026-03-04",
    created_by: "Jane Smith",
  },
  "PO-4510": {
    id: "PO-4510",
    vendor: "TechParts Inc",
    status: "Delivered",
    items: ["SSD 1TB x5", "RAM 32GB x10"],
    total: 3200.0,
    expected_delivery: "2026-02-18",
    created_by: "Bob Johnson",
  },
  "PO-4520": {
    id: "PO-4520",
    vendor: "Acme Corp",
    status: "Completed",
    items: ["Industrial Valve Set x2", "Pipe Fittings Kit x4"],
    total: 12500.0,
    expected_delivery: "2026-02-08",
    created_by: "Alice Brown",
  },
  "PO-4535": {
    id: "PO-4535",
    vendor: "Global Supplies Ltd",
    status: "Processing",
    items: ["Safety Helmets x100", "Gloves x200"],
    total: 8750.5,
    expected_delivery: "2026-03-12",
    created_by: "Tom Davis",
  },
};

export const USERS_DB = {
  "USR-101": {
    id: "USR-101",
    name: "Jane Smith",
    role: "Procurement Manager",
    department: "Admin",
    email: "jane.smith@company.com",
    last_login: "2026-03-02 09:15:00",
    account_status: "Active",
    locked: false,
  },
  "USR-102": {
    id: "USR-102",
    name: "Bob Johnson",
    role: "IT Specialist",
    department: "IT",
    email: "bob.johnson@company.com",
    last_login: "2026-03-01 14:30:00",
    account_status: "Active",
    locked: true,
  },
  "USR-103": {
    id: "USR-103",
    name: "Alice Brown",
    role: "Operations Lead",
    department: "Operations",
    email: "alice.brown@company.com",
    last_login: "2026-02-28 11:00:00",
    account_status: "Active",
    locked: false,
  },
};

export const COMMON_ERRORS = {
  "ERR-5001": {
    code: "ERR-5001",
    title: "Session Timeout",
    description: "User session has expired due to inactivity.",
    resolution: [
      "Log out and log back into the ERP system.",
      "Clear your browser cache and cookies.",
      "If the issue persists, check with IT if the session timeout policy was recently changed.",
    ],
    module: "Authentication",
    severity: "Low",
  },
  "ERR-5002": {
    code: "ERR-5002",
    title: "Insufficient Permissions",
    description: "User does not have the required role to perform this action.",
    resolution: [
      "Verify your current role in User Management, then My Profile.",
      "Request the necessary permissions from your department admin.",
      "If urgent, contact IT support to temporarily escalate your access.",
    ],
    module: "Authorization",
    severity: "Medium",
  },
  "ERR-5003": {
    code: "ERR-5003",
    title: "Database Connection Failed",
    description: "The ERP system cannot connect to the backend database.",
    resolution: [
      "Wait 2 to 3 minutes and try again, as this may be a temporary outage.",
      "Check the system status page for any ongoing maintenance.",
      "If the error continues, escalate to the DBA team immediately.",
    ],
    module: "System",
    severity: "Critical",
  },
  "ERR-5004": {
    code: "ERR-5004",
    title: "Invoice Posting Failed",
    description: "Invoice could not be posted due to a missing cost center.",
    resolution: [
      "Open the invoice in edit mode.",
      "Navigate to the Line Items tab and assign a valid cost center to each line.",
      "Save and retry posting.",
      "If cost centers are not available, contact your Finance team to configure them.",
    ],
    module: "Finance",
    severity: "Medium",
  },
  "ERR-5005": {
    code: "ERR-5005",
    title: "Duplicate Entry Detected",
    description: "A record with the same key already exists in the system.",
    resolution: [
      "Search for the existing record using the reference number.",
      "If this is a genuine duplicate, cancel the new entry.",
      "If the existing record is incorrect, archive it first then re-create.",
    ],
    module: "Master Data",
    severity: "Low",
  },
  "ERR-5006": {
    code: "ERR-5006",
    title: "GL Account Posting Error",
    description: "Transaction could not be posted because the GL account is closed or invalid for the current fiscal period.",
    resolution: [
      "Open the General Ledger module and go to Chart of Accounts.",
      "Search for the GL account number mentioned in the error.",
      "Check if the account status is Active and if the current fiscal period is open.",
      "If the period is closed, contact your Finance admin to reopen it or post to the correct period.",
      "If the GL account is inactive, select an alternative active account.",
    ],
    module: "General Ledger",
    severity: "Medium",
  },
  "ERR-5007": {
    code: "ERR-5007",
    title: "Approval Workflow Stuck",
    description: "An approval request is stuck in the workflow pipeline and not reaching the approver.",
    resolution: [
      "Go to Admin, then Workflow Management, then Pending Workflows.",
      "Search for the stuck request using the document number.",
      "Check the workflow log to see where it stopped.",
      "If the approver is unavailable, use the Reassign Approver button to route it to another authorized person.",
      "If the workflow engine is stuck, click Reset Workflow to restart the approval chain.",
    ],
    module: "Workflow",
    severity: "Medium",
  },
  "ERR-5008": {
    code: "ERR-5008",
    title: "Inventory Sync Mismatch",
    description: "Physical inventory count does not match the system quantity for one or more items.",
    resolution: [
      "Go to Inventory, then Stock Management, then Inventory Reconciliation.",
      "Run a Discrepancy Report for the affected warehouse.",
      "Review each mismatched item and verify the physical count.",
      "For confirmed discrepancies, create an Inventory Adjustment entry.",
      "Submit the adjustment for approval through the normal workflow.",
      "After approval, the system quantities will be updated to match the physical count.",
    ],
    module: "Inventory",
    severity: "Medium",
  },
  "ERR-5009": {
    code: "ERR-5009",
    title: "Payment Processing Failed",
    description: "The payment run failed to execute for one or more vendors.",
    resolution: [
      "Go to Finance, then Accounts Payable, then Payment Runs.",
      "Open the failed payment run and check the error log for each rejected payment.",
      "Common causes include: missing bank details on the vendor master, inactive vendor accounts, or exceeding payment limits.",
      "Fix the root cause for each failed payment, such as updating vendor bank details.",
      "Resubmit only the failed payments by selecting them and clicking Retry Selected.",
    ],
    module: "Finance",
    severity: "High",
  },
  "ERR-5010": {
    code: "ERR-5010",
    title: "Report Timeout Error",
    description: "The requested report took too long to generate and was terminated.",
    resolution: [
      "Try reducing the date range to a shorter period, for example one month instead of one year.",
      "Remove any complex custom filters and use the default report template first.",
      "If you need the full data set, try scheduling the report to run overnight via Report Center, then Scheduled Reports.",
      "You can also try exporting to CSV instead of PDF, as CSV generation is faster.",
      "If the issue persists, the DBA team may need to optimize the report query.",
    ],
    module: "Reporting",
    severity: "Low",
  },
};

export const SYSTEM_STATUS = {
  finance_module: { status: "Operational", last_checked: "2026-03-02 10:00:00" },
  procurement_module: { status: "Operational", last_checked: "2026-03-02 10:00:00" },
  hr_module: {
    status: "Degraded Performance",
    last_checked: "2026-03-02 09:45:00",
    note: "Slow response times due to scheduled index rebuild",
  },
  inventory_module: { status: "Operational", last_checked: "2026-03-02 10:00:00" },
  reporting_module: {
    status: "Under Maintenance",
    last_checked: "2026-03-02 08:00:00",
    note: "Scheduled maintenance until 12:00 PM UTC",
  },
  authentication: { status: "Operational", last_checked: "2026-03-02 10:00:00" },
};

export const NAVIGATION_GUIDE = {
  create_invoice: {
    path: "Finance > Accounts Payable > Create Invoice",
    steps: [
      "From the main dashboard, click on the Finance module.",
      "In the left sidebar, expand Accounts Payable.",
      "Click Create Invoice.",
      "Fill in the vendor, amount, cost center, and line items.",
      "Click Save Draft or Post to submit.",
    ],
  },
  approve_purchase_order: {
    path: "Procurement > Purchase Orders > Pending Approvals",
    steps: [
      "Go to the Procurement module from the main menu.",
      "Click Purchase Orders in the sidebar.",
      "Select Pending Approvals tab.",
      "Review the PO details and click Approve or Reject.",
    ],
  },
  reset_password: {
    path: "User Menu > My Profile > Security > Change Password",
    steps: [
      "Click your username in the top-right corner.",
      "Select My Profile.",
      "Go to the Security tab.",
      "Click Change Password.",
      "Enter your current password and set a new one.",
      "Click Save.",
    ],
  },
  run_report: {
    path: "Reporting > Report Center > Select Report Template",
    steps: [
      "Navigate to the Reporting module.",
      "Open the Report Center.",
      "Choose a report template or create a custom one.",
      "Set date range and filters.",
      "Click Generate Report.",
      "Download as PDF or Excel using the export button.",
    ],
  },
  manage_inventory: {
    path: "Inventory > Stock Management > Stock Overview",
    steps: [
      "Open the Inventory module.",
      "Click Stock Management in the sidebar.",
      "Select Stock Overview for a summary of all items.",
      "Use filters to search by warehouse, item code, or category.",
      "Click on any item for detailed stock movements.",
    ],
  },
  unlock_account: {
    path: "Admin > User Management > Search User > Unlock",
    steps: [
      "Go to the Admin module (requires admin role).",
      "Click User Management.",
      "Search for the locked user by name or ID.",
      "Open their profile and click Unlock Account.",
      "The user will receive an email confirmation.",
    ],
  },
  create_purchase_order: {
    path: "Procurement > Purchase Orders > Create New PO",
    steps: [
      "Open the Procurement module from the main menu.",
      "Click Purchase Orders in the left sidebar.",
      "Click the Create New PO button in the top right.",
      "Select the vendor from the dropdown or search by name.",
      "Add line items with item description, quantity, and unit price.",
      "Assign a cost center and budget code for each line item.",
      "Review the total amount and click Submit for Approval.",
      "The PO will be routed to the appropriate approver based on the amount.",
    ],
  },
  add_vendor: {
    path: "Procurement > Vendor Management > Add New Vendor",
    steps: [
      "Go to Procurement, then Vendor Management.",
      "Click Add New Vendor.",
      "Fill in the Basic Information tab: company name, tax ID, and contact details.",
      "Go to the Banking tab and enter the vendor's bank account details for payments.",
      "On the Terms tab, set the payment terms such as Net 30 or Net 60.",
      "Upload any required compliance documents on the Documents tab.",
      "Click Submit for Review. A procurement admin will approve the new vendor.",
    ],
  },
  view_gl_entries: {
    path: "Finance > General Ledger > Journal Entries",
    steps: [
      "Open the Finance module.",
      "Click General Ledger in the sidebar.",
      "Select Journal Entries to see all posted transactions.",
      "Use the filters at the top to narrow down by date range, GL account, or posting reference.",
      "Click on any entry to see the full debit and credit details.",
      "You can export the results using the Export button in the top right.",
    ],
  },
  submit_expense_report: {
    path: "HR > Employee Self-Service > Expense Reports > New Report",
    steps: [
      "Go to the HR module, then Employee Self-Service.",
      "Click Expense Reports.",
      "Click Create New Report.",
      "Enter a report title and select the expense period.",
      "Add each expense line: date, category such as travel or meals, amount, and attach the receipt.",
      "Review the total and click Submit for Approval.",
      "Your manager will receive a notification to review and approve the report.",
    ],
  },
  check_delivery_status: {
    path: "Procurement > Purchase Orders > Select PO > Delivery Tracking",
    steps: [
      "Open the Procurement module.",
      "Click Purchase Orders and find the PO you want to check.",
      "Open the PO and go to the Delivery Tracking tab.",
      "You'll see the current shipping status, carrier, and tracking number if available.",
      "If the status shows Delayed, click Flag Delay to notify the procurement team.",
    ],
  },
  configure_approval_workflow: {
    path: "Admin > Workflow Management > Approval Rules",
    steps: [
      "Go to Admin, then Workflow Management.",
      "Click Approval Rules.",
      "Select the document type you want to configure, such as Purchase Order or Invoice.",
      "Click Add Rule to create a new approval threshold.",
      "Set the amount range and assign the approver role or specific user.",
      "You can add multiple levels for higher amounts. For example, under 5000 dollars goes to the manager, over 5000 goes to the director.",
      "Click Save and Activate to put the rule into effect.",
    ],
  },
  inventory_adjustment: {
    path: "Inventory > Stock Management > Inventory Adjustment",
    steps: [
      "Open the Inventory module.",
      "Go to Stock Management, then Inventory Adjustment.",
      "Click Create New Adjustment.",
      "Select the warehouse and enter the item code.",
      "Enter the adjustment quantity (positive for additions, negative for reductions).",
      "Provide a reason code such as 'Damaged', 'Found', or 'Count Correction'.",
      "Add any notes explaining the adjustment.",
      "Click Submit for Approval. Your warehouse manager will need to approve it.",
    ],
  },
};

// ═══════════════════════════════════════════════════════════════════════════
// Verified Troubleshooting Knowledge Base
// ═══════════════════════════════════════════════════════════════════════════

export const TROUBLESHOOTING_KB = {
  login_failure: {
    title: "Cannot Log In / Login Failure",
    symptoms: ["can't log in", "login failed", "authentication error", "wrong password"],
    steps: [
      "First, make sure you are using the correct username. It usually starts with USR followed by a dash and your employee number.",
      "Try resetting your password by clicking Forgot Password on the login screen.",
      "Clear your browser cache and cookies, then try again.",
      "If your account is locked, contact your department admin or IT helpdesk to unlock it.",
      "As a last resort, try accessing the system from a different browser or incognito mode.",
    ],
    escalation_trigger: "If none of these steps work, this needs to be escalated to the IT Security team.",
    module: "Authentication",
    severity: "Medium",
  },
  slow_performance: {
    title: "System Running Slowly",
    symptoms: ["slow", "laggy", "takes forever", "hanging", "not responding"],
    steps: [
      "Check the system status page to see if any modules are under maintenance or degraded.",
      "Close any unused browser tabs and clear your browser cache.",
      "Try logging out and back in to refresh your session.",
      "If you are running a large report, consider narrowing the date range or filters.",
      "If the problem affects multiple users, this may be a server-side issue.",
    ],
    escalation_trigger: "If multiple users report slowness, escalate to the Infrastructure team.",
    module: "System",
    severity: "Medium",
  },
  report_not_loading: {
    title: "Report Won't Load or Generate",
    symptoms: ["report not loading", "report stuck", "can't generate report", "report error"],
    steps: [
      "Check if the Reporting module is currently under maintenance by viewing the system status.",
      "Ensure your date range is reasonable. Very large ranges can time out.",
      "Try using a different report template.",
      "Export to a different format, for example try Excel instead of PDF.",
      "If the report has custom filters, remove them and run the default version first.",
    ],
    escalation_trigger: "If no reports work for any user, escalate to the BI/Reporting team.",
    module: "Reporting",
    severity: "Low",
  },
  invoice_discrepancy: {
    title: "Invoice Amount or Status Mismatch",
    symptoms: ["wrong amount", "invoice mismatch", "invoice incorrect", "overcharged"],
    steps: [
      "First, pull up the invoice details using the invoice number.",
      "Compare the invoice amount with the linked purchase order.",
      "Check if any credit notes or adjustments have been applied.",
      "Verify the cost center and department allocation.",
      "If there is a genuine discrepancy, raise a dispute through Finance, then Accounts Payable, then Dispute Invoice.",
    ],
    escalation_trigger: "If the discrepancy involves amounts over ten thousand dollars, escalate to the Finance Manager.",
    module: "Finance",
    severity: "Medium",
  },
  po_delivery_delay: {
    title: "Purchase Order Delivery Delayed",
    symptoms: ["delivery late", "PO delayed", "hasn't arrived", "shipment delay"],
    steps: [
      "Look up the purchase order to check its current status and expected delivery date.",
      "If the status shows Shipped, the vendor may have tracking information.",
      "Contact the vendor using the information in the PO record.",
      "If the delivery is more than 5 business days overdue, flag it in the system.",
      "Go to Procurement, then Purchase Orders, find your PO and click Flag Delay.",
    ],
    escalation_trigger: "If the PO is critical or over 10 days late, escalate to the Procurement Manager.",
    module: "Procurement",
    severity: "Medium",
  },
  account_locked: {
    title: "User Account Is Locked",
    symptoms: ["account locked", "locked out", "can't access my account"],
    steps: [
      "Account locks usually happen after multiple failed login attempts.",
      "If you know the user ID, I can check the account status for you.",
      "To unlock an account, a system administrator needs to go to Admin, then User Management.",
      "They search for the user and click Unlock Account.",
      "The user will receive an email once the account is unlocked.",
    ],
    escalation_trigger: "If the admin portal is also inaccessible, escalate to the DBA team.",
    module: "Authentication",
    severity: "Medium",
  },
  data_export_failure: {
    title: "Cannot Export Data",
    symptoms: ["export failed", "download not working", "can't export", "excel download error"],
    steps: [
      "Make sure your browser allows pop-ups and downloads from the ERP domain.",
      "Try exporting in a different format. If PDF fails, try Excel or CSV.",
      "Reduce the data set by applying more filters before exporting.",
      "Clear your browser cache and try again.",
      "Check if your user role has the Export Data permission enabled.",
    ],
    escalation_trigger: "If export fails for all users, escalate to the Application Support team.",
    module: "System",
    severity: "Low",
  },
  permission_denied: {
    title: "Insufficient Permissions / Access Denied",
    symptoms: ["access denied", "permission denied", "not authorized", "can't access"],
    steps: [
      "Check your current role by going to your user profile.",
      "Your role determines what modules and actions you can access.",
      "If you need additional access, submit a request to your department admin.",
      "For urgent access, contact the IT helpdesk for a temporary role elevation.",
      "Make sure you're not trying to access a module that is currently under maintenance.",
    ],
    escalation_trigger: "If urgent and department admin is unavailable, escalate to IT Security.",
    module: "Authorization",
    severity: "Medium",
  },
  gl_posting_error: {
    title: "General Ledger Posting Error",
    symptoms: ["gl posting", "journal entry error", "posting failed", "fiscal period", "gl account"],
    steps: [
      "Check that the fiscal period for the posting date is open. Go to Finance, then Period Management to verify.",
      "Verify that the GL account you're posting to is active. Go to Finance, then Chart of Accounts and search for it.",
      "Make sure the debit and credit amounts are balanced. The total debits must equal total credits.",
      "Check that all required fields are filled in, including cost center, profit center, and posting description.",
      "If the period is closed, ask your Finance admin to either reopen it or help you post to the current open period.",
    ],
    escalation_trigger: "If the posting involves a period-end close adjustment, escalate to the Finance Controller.",
    module: "General Ledger",
    severity: "Medium",
  },
  payment_not_received: {
    title: "Vendor Payment Not Received",
    symptoms: ["payment not received", "vendor hasn't been paid", "payment missing", "payment delayed", "check not received"],
    steps: [
      "Look up the invoice to confirm it has been approved and the payment is due.",
      "Go to Finance, then Accounts Payable, then Payment History.",
      "Search by vendor name or invoice number to check if a payment was issued.",
      "If a payment was issued, check the payment method — ACH transfers typically take 2 to 3 business days, while checks take 5 to 7 days.",
      "If the payment shows as Sent but the vendor hasn't received it, verify the vendor's bank details in Vendor Management.",
      "For urgent cases, you can request an expedited payment from your Accounts Payable team.",
    ],
    escalation_trigger: "If the payment is for a critical vendor and is more than 7 days overdue, escalate to the AP Manager.",
    module: "Finance",
    severity: "Medium",
  },
  approval_stuck: {
    title: "Document Stuck in Approval Workflow",
    symptoms: ["approval stuck", "pending approval", "waiting for approval", "approver not responding", "workflow stuck"],
    steps: [
      "First, check the status of your document in the Pending Approvals section of the relevant module.",
      "Click on the document and check the Approval History tab to see who needs to approve.",
      "If the approver is out of office, you can ask an admin to reassign the approval.",
      "Go to Admin, then Workflow Management, then Pending Workflows.",
      "Find your document and click Reassign to route it to an alternate approver.",
      "If the workflow itself is stuck due to a system issue, an admin can click Reset Workflow to restart the approval chain.",
    ],
    escalation_trigger: "If this is blocking a time-sensitive transaction, escalate to the Workflow Admin.",
    module: "Workflow",
    severity: "Medium",
  },
  inventory_discrepancy: {
    title: "Inventory Count Doesn't Match System",
    symptoms: ["inventory mismatch", "stock count wrong", "quantity doesn't match", "inventory discrepancy", "missing stock"],
    steps: [
      "Go to Inventory, then Stock Management, then Inventory Reconciliation.",
      "Run a Discrepancy Report for the affected warehouse or item.",
      "Compare the system quantity with your actual physical count.",
      "Check the Stock Movement History for the item to see recent transactions — look for any goods receipts, issues, or transfers that might explain the difference.",
      "If you confirm a discrepancy, create an Inventory Adjustment entry to correct the system count.",
      "Provide a reason code and notes explaining the adjustment for audit purposes.",
    ],
    escalation_trigger: "If the discrepancy involves high-value items or exceeds 5% of total stock value, escalate to the Warehouse Manager.",
    module: "Inventory",
    severity: "Medium",
  },
  configuration_help: {
    title: "General ERP Configuration and Setup",
    symptoms: ["how to configure", "how to set up", "settings", "configuration", "customize"],
    steps: [
      "Most configuration settings are found in the Admin module under System Configuration.",
      "For module-specific settings, open the module and look for the Settings or Configuration option in the sidebar.",
      "Common configuration tasks include setting up approval thresholds, configuring email notifications, and managing user roles.",
      "Always test configuration changes in a non-production environment first if available.",
      "After making changes, log out and back in for the settings to take effect.",
    ],
    escalation_trigger: "For complex configuration changes that affect multiple modules, escalate to a System Administrator.",
    module: "System",
    severity: "Low",
  },
};

// ═══════════════════════════════════════════════════════════════════════════
// Deterministic Step Engine
// ═══════════════════════════════════════════════════════════════════════════

class StepEngine {
  static normalizeInvoiceId(raw) {
    raw = raw.trim().toUpperCase();
    if (!raw.startsWith("INV-")) {
      raw = `INV-${raw.replace(/^#|^0+/, "") || raw}`;
    }
    return raw;
  }

  static normalizePoId(raw) {
    raw = raw.trim().toUpperCase();
    if (!raw.startsWith("PO-")) {
      raw = `PO-${raw.replace(/^#/, "")}`;
    }
    return raw;
  }

  static normalizeErrorCode(raw) {
    raw = raw.trim().toUpperCase();
    if (!raw.startsWith("ERR-")) {
      raw = `ERR-${raw}`;
    }
    return raw;
  }

  lookupInvoice(invoiceId) {
    const normalized = StepEngine.normalizeInvoiceId(invoiceId);
    const invoice = INVOICES[normalized];
    if (invoice) return { found: true, data: invoice };
    return {
      found: false,
      error: `Invoice ${normalized} not found. Available invoices: ${Object.keys(INVOICES).join(", ")}.`,
    };
  }

  lookupPurchaseOrder(poId) {
    const normalized = StepEngine.normalizePoId(poId);
    const po = PURCHASE_ORDERS[normalized];
    if (po) return { found: true, data: po };
    return {
      found: false,
      error: `Purchase order ${normalized} not found. Available POs: ${Object.keys(PURCHASE_ORDERS).join(", ")}.`,
    };
  }

  lookupError(errorCode) {
    const normalized = StepEngine.normalizeErrorCode(errorCode);
    const error = COMMON_ERRORS[normalized];
    if (error) return { found: true, data: error };

    // Fuzzy search by keyword
    const keyword = errorCode.toLowerCase();
    for (const [code, err] of Object.entries(COMMON_ERRORS)) {
      if (err.title.toLowerCase().includes(keyword) || err.description.toLowerCase().includes(keyword)) {
        return { found: true, data: err };
      }
    }
    return {
      found: false,
      error: `Error code not found. Known codes: ${Object.keys(COMMON_ERRORS).join(", ")}.`,
    };
  }

  lookupUser(userQuery) {
    const upper = userQuery.trim().toUpperCase();
    if (upper.startsWith("USR-") && USERS_DB[upper]) {
      return { found: true, data: USERS_DB[upper] };
    }
    for (const [uid, user] of Object.entries(USERS_DB)) {
      if (user.name.toLowerCase().includes(userQuery.toLowerCase())) {
        return { found: true, data: user };
      }
    }
    return {
      found: false,
      error: `No user found matching '${userQuery}'. Try full name or user ID (e.g. USR-101).`,
    };
  }

  getSystemStatus(module = null) {
    if (module) {
      const key = module.trim().toLowerCase().replace(/ /g, "_");
      if (SYSTEM_STATUS[key + "_module"]) return { found: true, data: { [key]: SYSTEM_STATUS[key + "_module"] } };
      if (SYSTEM_STATUS[key]) return { found: true, data: { [key]: SYSTEM_STATUS[key] } };
    }
    return { found: true, data: SYSTEM_STATUS };
  }

  getNavigation(task) {
    const key = task.trim().toLowerCase().replace(/ /g, "_");
    const guide = NAVIGATION_GUIDE[key];
    if (guide) return { found: true, data: guide };

    // Fuzzy match
    for (const [navKey, val] of Object.entries(NAVIGATION_GUIDE)) {
      if (
        key.replace(/_/g, " ").includes(navKey.replace(/_/g, " ")) ||
        navKey.split("_").some((word) => word.length > 3 && key.includes(word))
      ) {
        return { found: true, data: val };
      }
    }
    return {
      found: false,
      available_tasks: Object.keys(NAVIGATION_GUIDE),
      error: "Task not found. Here are available tasks.",
    };
  }

  matchTroubleshooting(symptomsText) {
    const textLower = symptomsText.toLowerCase();
    let bestMatch = null;
    let bestScore = 0;

    for (const [key, entry] of Object.entries(TROUBLESHOOTING_KB)) {
      let score = 0;
      for (const symptom of entry.symptoms) {
        if (textLower.includes(symptom)) score++;
      }
      if (score > bestScore) {
        bestScore = score;
        bestMatch = { ...entry, _key: key };
      }
    }
    return bestScore > 0 ? bestMatch : null;
  }

  static shouldEscalate(confidence, severity = "Low", failedAttempts = 0, lowConfidenceCount = 0) {
    if (confidence < 0.4) return [true, "Very low confidence in understanding the request"];
    if (lowConfidenceCount >= 3) return [true, "Multiple consecutive low-confidence interactions"];
    if (failedAttempts >= 2) return [true, "User reported the issue persists after multiple attempts"];
    if (severity === "Critical" && failedAttempts >= 1) return [true, "Critical severity issue not resolved on first attempt"];
    return [false, ""];
  }
}

export const stepEngine = new StepEngine();

// ── Convenience standalone functions ─────────────────────────────────
export const normalizeInvoiceId = StepEngine.normalizeInvoiceId;
export const normalizePoId = StepEngine.normalizePoId;
export const normalizeErrorCode = StepEngine.normalizeErrorCode;
export const lookupInvoice = (id) => stepEngine.lookupInvoice(id);
export const lookupPurchaseOrder = (id) => stepEngine.lookupPurchaseOrder(id);
export const lookupError = (code) => stepEngine.lookupError(code);
export const lookupUser = (query) => stepEngine.lookupUser(query);
export const getSystemStatus = (module) => stepEngine.getSystemStatus(module);
export const getNavigation = (task) => stepEngine.getNavigation(task);
export function matchTroubleshooting(symptomsText) {
  const match = stepEngine.matchTroubleshooting(symptomsText);
  // Return array for compat with erpTools.js expectations
  return match ? [match] : [];
}
